### PR TITLE
Consider 'ITEM_PENDING_REVIEW' successful

### PR DESCRIPTION
**Pull request by bennbollay**
Publishing can return a status of ITEM_PENDING_REVIEW, which is a success response of the publishing process.

### CODE REVIEW

**Comment by fregante** [comment]
Isn’t “ITEM_PENDING_REVIEW” the response for when there’s *already* a version in review? Because in that situation, any uploads will fail (with this message, presumably)

**Comment by fregante** [comment]
The docs don’t give much explanation: https://developer.chrome.com/docs/webstore/webstore_api/items/publish/

**Comment by fregante** [comment]
Judging from other usage on GitHub, you appear to be correct: https://github.com/search?q=ITEM_PENDING_REVIEW&type=code

I’ll fix the test issues separately, they require an update of XO in a separate PR

**Comment by bennbollay** [comment]
I can confirm that there wasn't a version in review when I executed this code.  Beyond that, I can answer no further.

Thank you for your package and responsiveness!

**Comment by fregante** [comment]
Released, thank you for the PR https://github.com/fregante/chrome-webstore-upload-cli/releases/tag/v2.2.1

**Pull request merged**
